### ISSUE TITLE
Domain list keeps replicating itself.

### ISSUE THREAD

**Issue by AjisaiMirai** [dicedtomatoreal/typex#151]
I've recently started to use Zipline and for how it looks and works been happy with my choice.

However, the Domains list in the manage accounts tab keeps replicating the itself. To the point the array is quite large.
It looks like it just appends the old list into the new one and I'm not able to shrink/clean it, where I'd just have one domain in the list.

**Comment by diced** [comment]
This does seem to be a problem, though since you only have one domain you can just use that domain and not worry about the list. The list is for selecting random domains from a list of a few, and if you only have 1 it will just pick the same one over and over again. I'll be working on a fix for that soon though should be included in the next patch

**Comment by AmJustMirai** [comment]
> This does seem to be a problem, though since you only have one domain you can just use that domain and not worry about the list. The list is for selecting random domains from a list of a few, and if you only have 1 it will just pick the same one over and over again. I'll be working on a fix for that soon though should be included in the next patch

It's not a big deal, but it's choosing http alot over the few https entries. Mostly just prefer having the image url being https aswell. Other then that it's nothing major yea
