### ISSUE TITLE
Suggestion: (Extended) User management

### ISSUE THREAD

**Issue by lyrx2k** [dicedtomatoreal/typex#222]
### Suggestion

- Admin option to view ALL *(via the "Administration Tab")* files that have been uploaded
- Possibility to limit users with storage
- Possibility to limit users with file types
- Possibility to "lock" user accounts instead of having to delete them

Would be siiiiick

**Comment by TacticalTechJay** [comment]
- That's something I've pondered over as well.
- I doubt that'll be included, I did attempt it in a fork. (#201)j But dealing with merge conflicts while that issue was open was tough to keep up with.
- That's... a new one, what about admins?
- "lock" like prevent uploading (or even url shortcuts) or logging in?

**Comment by lyrx2k** [comment]
> * That's... a new one, what about admins?
> * "lock" like prevent uploading (or even url shortcuts) or logging in?

1. Admins shoult not can lock each other, the only one who should be able to lock such thinggs schould be the "super admin"
2. "lock" like prevent everything even the login (Login msg: "you are banned" or smth) :P

**Comment by diced** [comment]
Not sure of this will be in 3.6.1 but you may see it in 3.7 or 3.6.2.

**Comment by lyrx2k** [comment]
> Not sure of this will be in 3.6.1 but you may see it in 3.7 or 3.6.2.

awsome! :)
