### ISSUE TITLE
Bug: account list goes by highest id, not active account

### ISSUE THREAD

**Issue by superintendent2521** [dicedtomatoreal/typex#295]
### What happened?

how to repeat:

make multible accounts on instance, delete them all except for the one with the highest id, go to stats page and view it

images
![image](https://user-images.githubusercontent.com/67196752/220753566-b1052d09-6ae0-45ea-8dd9-6425e3650366.png)
http://upload.superintendent.me/u/h3LHBP.png

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Firefox

### Zipline Logs

```shell
no logs needed
```

### Browser Logs

```shell
no logs needed
```

### Additional Info

if logs are actually needed. please let me know and i will provide them

**Comment by superintendent2521** [comment]
update: highest account id is actually 5 but it shows 4 accounts,

**Comment by diced** [comment]
Reasons you may see 4 instead of 2 on the stats page is because they do not update instantly, they run on an interval to keep server load low (Querying hundreds or thousands of files every time you go to the stats page doesn't seem nice does it?).

Secondly, IDs start with 1, so if you have 4 accounts their ID's will be 1, 2, 3, 4.
