### ISSUE TITLE
Bug: .tar.gz files get changed to .gz

### ISSUE THREAD

**Issue by respektive** [dicedtomatoreal/typex#537]
### What happened?

Noticed while testing https://github.com/diced/zipline/issues/536. When uploading a .tar.gz file, the downloaded file will only have the .gz file extension. Unless you know you have to rename the file to .tar.gz, this basically breaks the archive. This does not happen when the "Keep Original Name" option is enabled. I'm assuming anything before the last period is just treated as the file name. Maybe a list of common file extensions could be checked first before falling back to the last period method.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
yeah ig the only way to handle this properly is to have a list of popular file extensions - I think I'll address this issue in v4 though. For the time being, this shouldn't really matter since whatever you use to extract these files should NOT be reading the file extension but some sort of file header within the first few bytes of the file - so it should still extract as a tar.gz!

**Comment by respektive** [comment]
Probably depends on the file archiver being used. I have tested on my machine running KDE using Ark and it didn't properly open it, the same way it opens a .tar.gz file, e.g. opening the whole archive directly instead of first showing the .tar file in the .gz file that has to be opened again. At first it didn't even show me that the file inside the gz archive is a tar file, which is why i originally wrote it's breaking the archive. That works today though, so no idea what the issue there was.

It's probably more a QOL change rather than a bug ig.

**Comment by diced** [comment]
> At first it didn't even show me that the file inside the gz archive is a tar file, which is why i originally wrote it's breaking the archive.

Interesting, I tried renaming a .tar.gz file to just .gz then opening it in Ark and it seemed to understand it fine, but you did say it seems to work now.

I'm gonna close this issue and put the thing about the common extensions on the v4 roadmap since it seems like a good idea to implement in the future.
