### ISSUE TITLE
Bug: Unexpected behaviours

### ISSUE THREAD

**Issue by brandonkal** [dicedtomatoreal/typex#555]
### What happened?

I tried Zipline to evaluate if it would be good for my use-case. A quick docker-compose up and it is clear I couldn't present this as a serious option. Below is a list of what I noticed.
1. Favoriting files makes them disappear. This shouldn't happen. Add them to the favorites list but don't remove them from the files list.
2. Link shortening copy doesn't work -- yes I know this requires https, so hide it in http.
3. Vanity shortens don't show the end result url
4. Clicking an audio file, the player is muted.
5. I cannot scrub forward in an audio file
6. I do not want uploaded files to be renamed
7. The interface is too busy (it appears there are two upload buttons (one specific to photos) in the files list
8. Likewise, I don't want to see stats (view count). I just want an easy way for someone to upload and manage files

Anyways, I thought I'd note these down so it can be improved for those who may someday find this software the right solution

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by lucius100** [comment]
max views also not working , visiting the shortened url doesn't increase the max views.
It would be good if you just list the bug instead asking the dev to remove existing feature.

**Comment by diced** [comment]
don't know why i left this unread for this long sorry

1. fixed in v4
2. I guess, I'll take a look into this
3. Not sure what this means?
4. this is intended
5. due to some unimplemented Range headers in v3, but they are included in v4
6. you can configure this lol
7. I think it's fine? you click upload and two options show up, one to upload any sort of file and then one to upload text with a built in (very limited) text editor which then you can syntax highlight and preview within the dashboard
8. I think adding some sort of way to disable stats is a good idea, I'll think about adding it in v4.

For now closing this issue, but feel free to comment on this since this seems to be more of feature requests/suggestions post instead of a bug report.
