### ISSUE TITLE
Bug: GPS data still present after adding EXIF_REMOVE_GPS .env variable

### ISSUE THREAD

**Issue by RestartB** [dicedtomatoreal/typex#578]
### What happened?

Unsure if I'm doing something wrong here. I added the following to my .env file:
```
EXIF_REMOVE_GPS=true
EXIF_ENABLED=false
```
then uploaded an image, but I noticed that the version I downloaded from Zipline still has the embedded GPS data present. When attempting to use the API to get EXIF data, I get error "403: exif disabled" so the changes to the .env file are taking effect, doesn't seem to be removing the GPS data though. Let me know if there's anything else I need to submit, do, or if I'm missing something - the image I'm uploading is a JPG file taken on my Pixel 7 Pro. Thanks!

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox

**Comment by RestartB** [comment]
Forgot to add, currently on version 3.7.9

**Comment by diced** [comment]
You have to have the `EXIF_ENABLED` variable set to true also, it should work then.

**Comment by RestartB** [comment]
Perfect, that worked. Thanks!

**Comment by MisterFixx** [comment]
Hello, I just verified that my env has

`EXIF_REMOVE_GPS=true`
`EXIF_ENABLED=true`

Additionally I also enabled 'Remove GPS Metadata' in the admin panel, however, when uploading an image taken by my iPhone 14 Pro Max to my Zipline v4.3.2 instance then downloading it, and checking its EXIF tags, I can see that the GPS coordinates are still there.

**Comment by diced** [comment]
looks like i didn't actually write the new buffer, it's now fixed in the latest commit (63c268cd1ee4500b093d9483d80e6f3fdcc4cc43). along with that, the variables you mentioned `EXIF_REMOVE_GPS` and `EXIF_ENABLED` are no longer a thing. The relevant environment variable is now `FILES_REMOVE_GPS_METADATA` (all you need is this one to be set to true and it'll start removing gps data, or you can search for "gps" in the settings page)

@MisterFixx
