### ISSUE TITLE
Bug: video embeds not playing on discord

### ISSUE THREAD

**Issue by not-nullptr** [dicedtomatoreal/typex#587]
### What happened?

video embeds don't seem to play back on discord. they do load, but the video says its 0 seconds long and won't play. here's an example URL to try, which doesn't load in discord. this isn't an issue with sharex or the server speed, as the video loads nearly instantly in-browser. 

http://nullptr.has.a.huge.slobbery.wang/u/Z7spGA.mp4

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
![image](https://github.com/user-attachments/assets/b5b20191-18b4-41c9-ad82-f45e73181313)

Seems like Discord just won't let you play videos that aren't HTTPS. I just changed http to https and it works as you can see in the image. If you want Zipline to return https urls instead of http, you need to set the `CORE_RETURN_HTTPS` environment variable to `true`. :)

**Comment by not-nullptr** [comment]
maybe this should be a default? not my place to say though, i don't get why anyone would host this over HTTP, its 2024 lol

thanks for the answer though!!
